/** Simple words a person can read back, say and type, for readable site passwords (site-auth.ts). */
export const PASSWORD_WORDS: readonly string[] = [
  'ant', 'ape', 'arch', 'arm', 'art', 'ash', 'bay', 'beam', 'bean', 'bear', 'bee', 'bell', 'belt', 'bird',
  'boat', 'bolt', 'bone', 'book', 'boot', 'bow', 'bowl', 'box', 'bud', 'bulb', 'bus', 'cake', 'calf', 'camp',
  'cane', 'cap', 'card', 'cart', 'cave', 'cedar', 'chair', 'chalk', 'chef', 'chip', 'city', 'clam', 'clay',
  'cliff', 'clock', 'cloud', 'coat', 'coin', 'comet', 'cone', 'coral', 'corn', 'cove', 'cow', 'crab',
  'crane', 'crow', 'cub', 'cup', 'dawn', 'deer', 'desk', 'dew', 'disc', 'dock', 'dove', 'drum', 'duck',
  'dune', 'eagle', 'earth', 'echo', 'elk', 'elm', 'fern', 'field', 'fig', 'fish', 'flag', 'flame', 'flute',
  'foam', 'fog', 'fox', 'frog', 'fruit', 'gate', 'gem', 'glass', 'glow', 'goat', 'gold', 'grape', 'grass',
  'gull', 'harp', 'hat', 'hawk', 'hay', 'heart', 'hill', 'hive', 'hook', 'horn', 'horse', 'ink', 'iris',
  'isle', 'ivy', 'jade', 'jar', 'jet', 'kale', 'key', 'kite', 'lake', 'lamp', 'lark', 'leaf', 'lemon',
  'lily', 'lime', 'lion', 'log', 'loom', 'lotus', 'lynx', 'maple', 'map', 'mars', 'mast', 'meadow', 'melon',
  'mesa', 'mint', 'moon', 'moose', 'moss', 'moth', 'mule', 'nest', 'net', 'nut', 'oak', 'oar', 'oat',
  'ocean', 'olive', 'onyx', 'orbit', 'otter', 'owl', 'palm', 'pear', 'pearl', 'pen', 'pine', 'pipe', 'plum',
  'pond', 'pony', 'quail', 'quill', 'rain', 'ram', 'raven', 'reed', 'reef', 'ridge', 'ring', 'river',
  'robin', 'rock', 'roof', 'rose', 'ruby', 'sage', 'sail', 'salt', 'sand', 'seal', 'seed', 'shell', 'ship',
  'silk', 'sky', 'sled', 'slope', 'snow', 'sock', 'sol', 'spark', 'star', 'stem', 'stone', 'storm', 'straw',
  'sun', 'swan', 'tea', 'teal', 'tent', 'tide', 'tiger', 'toad', 'torch', 'tower', 'trail', 'tree', 'tulip',
  'twig', 'vale', 'vase', 'vine', 'violet', 'wave', 'whale', 'wheat', 'willow', 'wind', 'wing', 'wolf',
  'wood', 'wren', 'yak', 'yarn', 'zebra', 'apple', 'aspen', 'badge', 'basil', 'berry', 'birch', 'blaze',
  'brook', 'cabin', 'candle', 'canoe', 'cherry', 'clover', 'cocoa', 'copper', 'cotton', 'daisy', 'delta',
  'ember', 'fable', 'falcon', 'forest', 'frost', 'garden', 'ginger', 'glade', 'granite', 'harbor', 'hazel',
  'honey', 'island', 'jasmine', 'juniper', 'lagoon', 'lantern', 'laurel', 'linen', 'magnet', 'marble',
  'meteor', 'mocha', 'nectar', 'oasis', 'opal', 'orchid', 'panda', 'pebble', 'pepper', 'piano', 'planet',
  'poppy', 'prism', 'quartz', 'rocket', 'saffron', 'salmon', 'sierra', 'silver', 'sparrow', 'spruce',
  'summit', 'sunset', 'thistle', 'thunder', 'timber', 'topaz', 'tundra', 'valley', 'velvet', 'walnut',
  'winter',
];
