import { existsSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

// Computed independently rather than importing `BOT_DIR` from `runner.ts`:
// `runner.ts` needs to import `db/run-sync.ts`, which needs this module, so
// importing back from `runner.ts` here would be a circular import (and,
// since `runner.ts`'s own `BOT_DIR` is a top-level `const`, a real TDZ crash
// depending on which module happens to finish evaluating first). Same
// directory as `runner.ts`, so the relative path is identical.
const BOT_DIR = resolve(import.meta.dirname, '..', '..', 'seek-bot');

/**
 * Per-account private directory: `seek-bot/data/users/<userId>/`.
 *
 * This is what makes a spawned run (and the dashboard's own file storage)
 * belong to exactly one account instead of the single shared `seek-bot/data/`
 * folder every account used to read and write. Its contents split into two
 * kinds:
 *
 *  - Canonical here, nowhere else: the actual résumé/knowledge binary files
 *    (`resumes/`, `knowledge/` — Postgres only stores their metadata) and
 *    `queue.json` (the extension's review queue; there is no `queue_items`
 *    table, so this directory *is* its durable home, not just a run-time
 *    cache).
 *  - A disposable export of Postgres, regenerated by `db/run-sync.ts`
 *    immediately before every run: `profile.txt`, `resumes.json`,
 *    `knowledge.json`, `applied.json`. Never treat these as a second source
 *    of truth — Postgres is authoritative and can always regenerate them.
 */

export const USERS_DIR = resolve(BOT_DIR, 'data', 'users');

export function userDir(userId: string): string {
  return resolve(USERS_DIR, String(userId));
}

export function userResumeDir(userId: string): string {
  return resolve(userDir(userId), 'resumes');
}

export function userKnowledgeDir(userId: string): string {
  return resolve(userDir(userId), 'knowledge');
}

function ensure(dir: string) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

/** Creates the account's directory (and its resumes/knowledge subfolders) if needed. */
export function ensureUserDataDir(userId: string): string {
  const dir = userDir(userId);
  ensure(dir);
  ensure(userResumeDir(userId));
  ensure(userKnowledgeDir(userId));
  return dir;
}
