export const AUSTRALIAN_CITIES = [
  'Sydney',
  'Melbourne',
  'Brisbane',
  'Perth',
  'Adelaide',
  'Canberra',
  'Hobart',
  'Darwin',
  'Gold Coast',
  'Newcastle',
  'Wollongong',
  'Geelong',
  'Sunshine Coast',
  'Townsville',
  'Cairns',
  'Toowoomba',
  'Ballarat',
  'Bendigo',
  'Launceston',
  'Mackay',
  'Rockhampton',
  'Bunbury',
  'Coffs Harbour',
  'Wagga Wagga',
  'Albury',
  'Hervey Bay',
  'Mildura',
  'Shepparton',
  'Port Macquarie',
  'Gladstone',
] as const;
