import { useCallback, useEffect, useState } from 'react';
import type { MarketingArticle, MarketingPost, MarketingSite, MarketingWorkspace } from '../marketingTypes';
import './MarketingAgent.css';

async function api<T>(path:string,method='GET',body?:unknown):Promise<T> {
  const response=await fetch(`/api/marketing/${path}`,{method,headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const value=await response.json();if(!response.ok) throw new Error(value.error || 'Request failed.');return value;
}
const markets:Record<string,string>={AU:'Australia',US:'United States',GB:'United Kingdom',CA:'Canada',NZ:'New Zealand',IN:'India',SG:'Singapore',DE:'Germany',FR:'France'};
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const date=(value:string)=>new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});

export function MarketingAgent() {
  const [sites,setSites]=useState<MarketingSite[]>([]),[selected,setSelected]=useState(''),[data,setData]=useState<MarketingWorkspace|null>(null);
  const [url,setUrl]=useState(''),[country,setCountry]=useState('AU'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[configured,setConfigured]=useState(true);
  const loadSites=useCallback(async()=>{const r=await api<{sites:MarketingSite[];writerConfigured:boolean}>('sites');setSites(r.sites);setConfigured(r.writerConfigured);setSelected(prev=>prev || r.sites[0]?.id || '');},[]);
  const refresh=useCallback(async()=>{if(selected) setData(await api<MarketingWorkspace>(`sites/${selected}`));},[selected]);
  useEffect(()=>{void loadSites().catch(e=>setError(e.message));},[loadSites]);
  useEffect(()=>{setData(null);void refresh().catch(e=>setError(e.message));},[refresh]);
  const running=data?.jobs.some(j=>j.status==='queued'||j.status==='running') || false;
  useEffect(()=>{if(!selected) return;const timer=setInterval(()=>void refresh().catch(e=>setError(e.message)),running?3000:15000);return()=>clearInterval(timer);},[selected,running,refresh]);
  const act=async(work:()=>Promise<unknown>,message='Saved')=>{setBusy(true);setError('');setNotice('');try{await work();await refresh();await loadSites();setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const path=`sites/${selected}`;
  return <div className="marketing-agent">
    <div className="ma-intro"><span className="ma-badge">Marketing beta</span><h2>Your website. A useful blog plan.</h2><p>We read your products, find competitors in the browser and use Gemini to plan and write sourced blogs.</p><ol className="ma-steps"><li>Enter website</li><li>Check your products</li><li>Choose topics</li><li>Review or schedule</li></ol></div>
    {error && <div className="ma-alert" role="alert">{error}</div>}{notice && <p role="status" className="ma-notice">{notice}</p>}
    {!configured && <div className="ma-alert">Gemini needs an API key. An admin can add it in Admin → Config → Weekly blog.</div>}
    <form className="ma-card ma-add" onSubmit={e=>{e.preventDefault();void act(async()=>{const r=await api<{site:MarketingSite}>('sites','POST',{url,country});setSelected(r.site.id);setUrl('');},'Your website research is queued. You can leave this page and return.');}}>
      <label>Website URL<input type="url" required placeholder="https://your-website.com" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Target market<select value={country} onChange={e=>setCountry(e.target.value)}>{Object.entries(markets).map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><button disabled={busy||!configured}>Build my marketing plan</button>
    </form>
    {sites.length>0 && <label className="ma-select">Your websites<select value={selected} onChange={e=>{setSelected(e.target.value);setNotice('');setError('');}}>{sites.map(s=><option key={s.id} value={s.id}>{s.name || new URL(s.url).hostname}</option>)}</select></label>}
    {selected && !data && <p>Loading your workspace…</p>}
    {data && <>
      <div className="ma-summary"><div><h2>{data.site.name || new URL(data.site.url).hostname}</h2><a href={data.site.url} target="_blank" rel="noreferrer">Visit website ↗</a></div><div><strong>{data.topics.filter(t=>t.status==='planned').length}</strong> planned topics</div><div><strong>{data.posts.filter(p=>p.status==='draft').length}</strong> drafts</div><div><strong>{data.posts.filter(p=>p.status==='published').length}</strong> published</div></div>
      {data.jobs.filter(j=>j.status==='queued'||j.status==='running').map(j=><div className="ma-progress" role="status" key={j.id}><strong>{j.status==='queued'?'Queued':'Working'} · {j.kind==='cycle'?'Weekly blog':j.kind}</strong><p>{j.progress}</p>{j.error && <p>{j.error}</p>}<small>Work continues if you close this page. Browser blocks are reported as research gaps.</small></div>)}
      {!running && data.jobs[0]?.status==='failed' && <div className="ma-alert">{data.jobs[0].error}<p>Refresh research, or open the topic or draft below and try again.</p></div>}
      {data.site.profile ? <Profile site={data.site} disabled={busy||running} onSave={b=>act(()=>api(path,'PATCH',b),'Website profile saved.')} onResearch={()=>act(()=>api(`${path}/research`,'POST',{}),'Research queued.')} /> : <div className="ma-card"><h3>1. Website scan</h3><p>The scan will identify your products and suggest an audience. You’ll confirm it before any drafts or schedules start.</p>{!running && <button disabled={busy} onClick={()=>void act(()=>api(`${path}/research`,'POST',{}),'Research queued.')}>Retry website research</button>}</div>}
      {data.site.research && <details className="ma-card"><summary>Research evidence and website improvements</summary><p>Checked {date(data.site.research.researchedAt)} · {data.site.research.retained} usable evidence records.</p><p className="ma-muted">Scout usage estimate: {data.site.research.cost || 'Unavailable'} (Gemini writing is separate).</p><h4>Verified competitor leads</h4>{data.site.research.competitors.length?data.site.research.competitors.map(c=><p key={c.website}><a href={c.website} target="_blank" rel="noreferrer">{c.name} ↗</a> — {c.region}<br/><small>{c.productQuote}</small></p>):<p>No competitor was verified in this bounded search.</p>}<h4>Browser searches</h4>{data.site.research.searches.map((s,i)=><p key={i}>{s.engine}: {s.query} · {s.status} · {s.leads} leads</p>)}<h4>Website improvements</h4>{data.site.research.auditActions.length?data.site.research.auditActions.map((a,i)=><p key={i}><a href={a.url} target="_blank" rel="noreferrer">Page ↗</a>: {a.issue}<br/>{a.action}</p>):<p>No improvement was identified by these limited page checks.</p>}<h4>Research limits</h4><ul>{data.site.research.gaps.map((g,i)=><li key={i}>{g}</li>)}</ul></details>}
      <section className="ma-card"><h3>2. Your content plan</h3><p>Decision topics get priority because they help a buyer choose. Search volume and conversion performance are unmeasured.</p>{!data.topics.length && <p>Topics appear after the research finishes.</p>}<div className="ma-topics">{data.topics.filter(t=>t.status!=='dismissed').map(t=><article key={t.id}><div className="ma-row"><span className="ma-badge">{t.intent==='buy'?'Buyer decision':t.intent==='compare'?'Comparison':'Helpful guide'}</span><small>{t.status}</small></div><h4>{t.title}</h4><p>{t.angle}</p><small>Focus: {t.keyword} · {t.basis==='search-suggestion'?'Observed search suggestion':t.basis==='custom'?'Your idea':'Suggested from website content'}</small><p className="ma-muted">{t.rationale}</p><details><summary>Evidence and product link</summary>{t.evidenceUrls.map((u,i)=><p key={u}><a href={u} target="_blank" rel="noreferrer">Source {i+1} ↗</a></p>)}<a href={t.productUrl} target="_blank" rel="noreferrer">Product / landing page ↗</a></details>{t.status==='planned' && <div className="ma-actions"><button disabled={busy||running||!data.site.profileConfirmed} onClick={()=>void act(()=>api(`${path}/drafts`,'POST',{topicId:t.id}),'Gemini draft queued.')}>Create draft</button><button className="ma-secondary" disabled={busy||running} onClick={()=>void act(()=>api(`${path}/topics/${t.id}`,'PATCH',{status:'dismissed'}),'Topic skipped.')}>Skip</button></div>}</article>)}</div><details className="ma-custom"><summary>Add your own topic</summary><CustomTopic disabled={busy||running} onAdd={b=>act(()=>api(`${path}/topics`,'POST',b),'Topic added.')}/></details></section>
      <section className="ma-card"><h3>3. Drafts and published posts</h3>{!data.posts.length && <p>Create a draft from a topic above. Gemini writes it and checks factual claims against the collected sources.</p>}{data.posts.map(post=><Draft key={post.id} post={post} path={path} disabled={busy||running} canPublish={data.canPublish} act={act}/>)}</section>
      <Schedule key={data.site.id} site={data.site} canPublish={data.canPublish} disabled={busy} onSave={b=>act(()=>api(path,'PATCH',b),'Weekly schedule saved.')} />
      <details className="ma-card"><summary>Recent activity</summary>{data.jobs.map(j=><p key={j.id}>{date(j.createdAt)} · {j.kind} · {j.status}<br/><small>{j.error || j.progress}</small></p>)}</details>
    </>}
  </div>;
}

function Profile({site,disabled,onSave,onResearch}:{site:MarketingSite;disabled:boolean;onSave:(b:unknown)=>Promise<void>;onResearch:()=>Promise<void>}) {
  const [voice,setVoice]=useState(site.voice),[audience,setAudience]=useState(site.audience || site.profile?.suggestedAudience || ''),[ctaLabel,setCtaLabel]=useState(site.ctaLabel),[ctaUrl,setCtaUrl]=useState(site.ctaUrl),[confirmed,setConfirmed]=useState(site.profileConfirmed);
  useEffect(()=>setConfirmed(site.profileConfirmed),[site.profileConfirmed]);
  return <section className="ma-card"><div className="ma-row"><h3>1. Check your website profile</h3><button className="ma-secondary" disabled={disabled} onClick={()=>void onResearch()}>Refresh research</button></div><p><strong>What you sell:</strong> {site.profile?.sells}</p><details><summary>Product evidence · {site.profile?.pages.length} pages scanned</summary>{site.profile?.productQuotes.map((q,i)=><blockquote key={i}>{q.quote}<br/><a href={q.url} target="_blank" rel="noreferrer">Check source ↗</a></blockquote>)}</details><form onSubmit={e=>{e.preventDefault();void onSave({voice,audience,ctaLabel,ctaUrl,profileConfirmed:confirmed});}}><div className="ma-grid"><label>Audience <small>(suggested; edit for your customers)</small><textarea value={audience} onChange={e=>setAudience(e.target.value)} maxLength={1200}/></label><label>Brand voice<textarea value={voice} onChange={e=>setVoice(e.target.value)} maxLength={600}/></label><label>Call to action<input required value={ctaLabel} onChange={e=>setCtaLabel(e.target.value)} maxLength={100}/></label><label>Call-to-action URL <small>(on your website)</small><input type="url" required value={ctaUrl} onChange={e=>setCtaUrl(e.target.value)}/></label></div><label className="ma-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the product description and target audience.</label><button disabled={disabled}>Save website profile</button></form></section>;
}

function CustomTopic({disabled,onAdd}:{disabled:boolean;onAdd:(b:unknown)=>Promise<void>}) {const [title,setTitle]=useState(''),[keyword,setKeyword]=useState('');return <form className="ma-add" onSubmit={e=>{e.preventDefault();void onAdd({title,keyword}).then(()=>{setTitle('');setKeyword('');});}}><label>Blog title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Focus topic<input required maxLength={120} value={keyword} onChange={e=>setKeyword(e.target.value)}/></label><button disabled={disabled}>Add topic</button></form>;}

function Schedule({site,canPublish,disabled,onSave}:{site:MarketingSite;canPublish:boolean;disabled:boolean;onSave:(b:unknown)=>Promise<void>}) {
  const [enabled,setEnabled]=useState(site.scheduleEnabled),[mode,setMode]=useState(site.publishMode),[day,setDay]=useState(site.scheduleDay),[time,setTime]=useState(site.scheduleTime),[timezone,setTimezone]=useState(site.timezone);
  useEffect(()=>{setEnabled(site.scheduleEnabled);setMode(site.publishMode);setDay(site.scheduleDay);setTime(site.scheduleTime);setTimezone(site.timezone);},[site.scheduleEnabled,site.publishMode,site.scheduleDay,site.scheduleTime,site.timezone]);
  return <section className="ma-card"><h3>4. One blog every week</h3><p>The agent refreshes research when needed, selects a planned topic and prepares one blog. You can pause at any time.</p>{!canPublish && <p className="ma-muted">Weekly drafts work for this website. Automatic publishing currently supports Owtomate’s built-in blog; export other website drafts to your CMS.</p>}{canPublish && <p className="ma-muted">Enabling this schedule replaces Owtomate’s legacy weekly blog schedule. Pausing here keeps the legacy publisher paused too.</p>}<form onSubmit={e=>{e.preventDefault();void onSave({scheduleEnabled:enabled,publishMode:mode,scheduleDay:day,scheduleTime:time,timezone});}}><label className="ma-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enable weekly blogs</label><div className="ma-grid"><label>Day<select value={day} onChange={e=>setDay(Number(e.target.value))}>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label>Local time<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>Timezone<input required value={timezone} onChange={e=>setTimezone(e.target.value)} list="ma-timezones"/><datalist id="ma-timezones">{['Australia/Sydney','Australia/Perth','Pacific/Auckland','America/New_York','America/Los_Angeles','Europe/London','Asia/Kathmandu','UTC'].map(t=><option key={t} value={t}/>)}</datalist></label><label>What happens<select value={mode} onChange={e=>setMode(e.target.value as 'review'|'auto')}><option value="review">Create draft for my review</option>{canPublish && <option value="auto">Publish after source checks</option>}</select></label></div><p>{site.scheduleEnabled&&site.nextRunAt?`Next run: ${date(site.nextRunAt)} (${site.timezone})`:'Schedule is paused.'}</p><button disabled={disabled||!site.profileConfirmed}>Save weekly schedule</button>{!site.profileConfirmed && <p className="ma-muted">Confirm the website profile first.</p>}</form></section>;
}

function Draft({post,path,disabled,canPublish,act}:{post:MarketingPost;path:string;disabled:boolean;canPublish:boolean;act:(work:()=>Promise<unknown>,message?:string)=>Promise<void>}) {
  const [editing,setEditing]=useState(false),[article,setArticle]=useState<MarketingArticle|null>(post.article),[copied,setCopied]=useState(false);
  useEffect(()=>{if(!editing) setArticle(post.article);},[post.updatedAt,post.article,editing]);
  if(!post.article || !article) return <div className="ma-draft"><h4>{post.status==='failed'?'Writing needs attention':'Preparing draft…'}</h4></div>;
  const endpoint=`${path}/posts/${post.id}`;
  const set=(key:'title'|'metaDescription'|'lead',value:string)=>setArticle({...article,[key]:value});
  const section=(i:number,key:'heading'|'paragraphs'|'bullets',value:string)=>setArticle({...article,sections:article.sections.map((s,j)=>i===j?{...s,[key]:key==='heading'?value:value.split('\n\n').map(v=>v.trim()).filter(Boolean)}:s)});
  return <details className="ma-draft"><summary>{post.article.title} <span className="ma-badge">{post.status==='published'?'Published':post.quality.approved?'Source review passed':'Needs source review'}</span></summary><p>Focus: {post.article.focusKeyword} · Writer: Gemini · {date(post.updatedAt)}</p>{post.quality.issues.length>0 && <div className="ma-alert"><ul>{post.quality.issues.map((s,i)=><li key={i}>{s}</li>)}</ul></div>}{editing?<form onSubmit={e=>{e.preventDefault();void act(()=>api(endpoint,'PATCH',{article,updatedAt:post.updatedAt}),'Draft saved. Run source review before publishing.').then(()=>setEditing(false));}}><label>Title<input required value={article.title} onChange={e=>set('title',e.target.value)}/></label><label>Search description<textarea value={article.metaDescription} onChange={e=>set('metaDescription',e.target.value)}/></label><label>Introduction<textarea value={article.lead} onChange={e=>set('lead',e.target.value)}/></label>{article.sections.map((s,i)=><fieldset key={i}><legend>Section {i+1}</legend><label>Heading<input value={s.heading} onChange={e=>section(i,'heading',e.target.value)}/></label><label>Paragraphs <small>(blank line between each)</small><textarea rows={6} value={s.paragraphs.join('\n\n')} onChange={e=>section(i,'paragraphs',e.target.value)}/></label><label>Bullets <small>(blank line between each)</small><textarea value={s.bullets.join('\n\n')} onChange={e=>section(i,'bullets',e.target.value)}/></label></fieldset>)}<label>Takeaways <small>(blank line between each)</small><textarea value={article.takeaways.join('\n\n')} onChange={e=>setArticle({...article,takeaways:e.target.value.split('\n\n').filter(Boolean)})}/></label><div className="ma-actions"><button disabled={disabled}>Save edits</button><button type="button" className="ma-secondary" onClick={()=>{setEditing(false);setArticle(post.article);}}>Cancel</button></div></form>:<><p className="ma-muted">{post.article.metaDescription}</p><p>{post.article.lead}</p>{post.article.sections.map((s,i)=><div key={i}><h4>{s.heading}</h4>{s.paragraphs.map((p,j)=><p key={j}>{p}</p>)}<ul>{s.bullets.map((b,j)=><li key={j}>{b}</li>)}</ul></div>)}<h4>Key takeaways</h4><ul>{post.article.takeaways.map((t,i)=><li key={i}>{t}</li>)}</ul></>}
    <details><summary>Check sources</summary>{post.sources.map(s=><p key={s.ref}>[{s.ref}] <a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><br/><small>{s.collectedAt?`Collected ${date(s.collectedAt)}`:'Collection date unavailable'}</small></p>)}</details>
    <div className="ma-actions">{post.status==='draft' && !editing && <><button className="ma-secondary" disabled={disabled} onClick={()=>setEditing(true)}>Edit draft</button><button className="ma-secondary" disabled={disabled} onClick={()=>void act(()=>api(`${endpoint}/review`,'POST',{}),'Source review queued.')}>Review sources</button>{canPublish && <button disabled={disabled||!post.quality.approved} onClick={()=>void act(()=>api(`${endpoint}/publish`,'POST',{}),'Publication queued. Sources will be checked again.')}>Publish to Owtomate</button>}</>}<a href={`/api/marketing/${endpoint}/export?format=html`}>Download HTML</a><a href={`/api/marketing/${endpoint}/export?format=markdown`}>Download Markdown</a>{post.publishedUrl && <a href={post.publishedUrl} target="_blank" rel="noreferrer">Read live post ↗</a>}</div>
    {post.publishedUrl && <><button className="ma-secondary" onClick={()=>{const u=new URL(post.publishedUrl!);u.searchParams.set('utm_source','social');u.searchParams.set('utm_medium','organic');u.searchParams.set('utm_campaign','blog');void navigator.clipboard.writeText(`${post.article!.title}\n\n${post.article!.metaDescription}\n\n${u.href}`).then(()=>setCopied(true));}}>{copied?'Share text copied':'Copy social share text'}</button><Metrics post={post} disabled={disabled} onSave={b=>act(()=>api(`${endpoint}/metrics`,'PATCH',b),'Measured results saved.')}/></>}
  </details>;
}

function Metrics({post,disabled,onSave}:{post:MarketingPost;disabled:boolean;onSave:(b:unknown)=>Promise<void>}) {
  const m=post.metrics;
  return <details className="ma-custom"><summary>Record actual results</summary><p>Use your analytics or sales records. Leave unknown numbers blank; zero means measured zero. Saving replaces this post’s previous measurement period.</p>{m && <p>{m.periodStart}–{m.periodEnd}: {m.visits??'Unknown'} visits · {m.leads??'Unknown'} leads · {m.orders??'Unknown'} orders · {m.revenue==null?'Unknown revenue':`${m.currency} ${m.revenue}`}{m.visits!=null&&m.visits>0&&m.leads!=null?` · ${(m.leads/m.visits*100).toFixed(1)}% visits to leads`:''}</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const body:Record<string,unknown>=Object.fromEntries(f);for(const key of ['visits','leads','orders','revenue']) body[key]=f.get(key)===''?null:Number(f.get(key));void onSave(body);}}><div className="ma-grid"><label>From<input type="date" name="periodStart" required defaultValue={m?.periodStart}/></label><label>To<input type="date" name="periodEnd" required max={new Date().toISOString().slice(0,10)} defaultValue={m?.periodEnd}/></label>{['visits','leads','orders','revenue'].map(key=><label key={key}>{key}<input name={key} type="number" min="0" step={key==='revenue'?'0.01':'1'} defaultValue={m?.[key as 'visits']??''}/></label>)}<label>Currency<input name="currency" maxLength={3} defaultValue={m?.currency||'AUD'}/></label><label>Measurement source / notes<input name="notes" maxLength={600} defaultValue={m?.notes}/></label></div><button disabled={disabled}>Save measured results</button></form></details>;
}
