import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { getPool, one, query } from '../db/index.js';
import { enqueue, iso, ownedSite, saveDraft, saveMetrics, updateSite, workspace } from './store.js';
import { marketingTick, queueDueSchedules } from './worker.js';

test('real PostgreSQL migration, ownership, queue uniqueness, edits and weekly idempotency',{skip:process.env.RUN_MARKETING_DB_TESTS!=='1'},async()=>{
  const schema=`marketing_qa_${randomUUID().replace(/-/g,'')}`;
  process.env.PGOPTIONS=`-c search_path=${schema}`;
  const pool=getPool();
  const oldFetch=globalThis.fetch;
  const keys=['ADMIN_EMAILS','APP_BASE_URL','GEMINI_API_KEY','BLOG_GEMINI_MODEL'] as const;
  const oldEnv=Object.fromEntries(keys.map(k=>[k,process.env[k]]));
  try {
    await pool.query(`CREATE SCHEMA ${schema}`);
    const sql=readFileSync(new URL('../db/schema.sql',import.meta.url),'utf8');
    await pool.query(sql);await pool.query(sql);
    const users=await query<{id:string}>("INSERT INTO users(email) VALUES('owner@marketing-qa.invalid'),('other@marketing-qa.invalid') RETURNING id");
    const user=users[0].id,other=users[1].id,site=randomUUID(),topic=randomUUID(),post=randomUUID();
    await query("INSERT INTO marketing_sites(id,user_id,url,cta_url,profile_confirmed,profile,research) VALUES($1,$2,'https://example.com/','https://example.com/',true,$3,$4)",[site,user,{sells:'software',pages:[{url:'https://example.com/'}]},{researchedAt:new Date().toISOString()}]);
    assert.equal((await workspace(user,site,false)).site.id,site);
    await assert.rejects(ownedSite(other,site),/not found/);
    await assert.rejects(updateSite(other,site,false,{voice:'attack'}),/not found/);
    await assert.rejects(enqueue(other,site,false,'research'),/not found/);
    await query("INSERT INTO marketing_topics(id,site_id,user_id,topic_key,title,keyword,angle,intent,priority,rationale,product_url,basis) VALUES($1,$2,$3,'topic','Topic','topic','Help','learn','medium','Advice','https://example.com/','custom')",[topic,site,user]);
    const job=await enqueue(user,site,false,'write',topic);
    await assert.rejects(enqueue(user,site,false,'write',topic),/in progress/);
    await assert.rejects(query("INSERT INTO marketing_jobs(id,site_id,user_id,kind,idempotency_key) VALUES($1,$2,$3,'research','bad-owner')",[randomUUID(),site,other]),e=>(e as {code:string}).code==='23503');
    await query("UPDATE marketing_jobs SET status='done' WHERE id=$1",[job.id]);
    const article={title:'Helpful article',slug:'helpful',metaDescription:'A guide',focusKeyword:'topic',targetSearches:[],lead:'Product information [S1]',sections:[{heading:'One',paragraphs:[Array(80).fill('Useful practical guidance.').join(' ')],bullets:[]},{heading:'Two',paragraphs:[Array(80).fill('Choose what fits.').join(' ')],bullets:[]}],takeaways:['Check your needs.']};
    await query("INSERT INTO marketing_posts(id,site_id,user_id,topic_id,status,article,brief,quality) VALUES($1,$2,$3,$4,'draft',$5,$6,$7)",[post,site,user,topic,article,{sources:[{ref:'S1'}]},{approved:true,issues:[],reviewedAt:new Date().toISOString()}]);
    const before=await one('SELECT updated_at FROM marketing_posts WHERE id=$1',[post]);
    await assert.rejects(saveDraft(other,site,post,{article,updatedAt:iso(before!.updated_at)}),/not found/);
    await assert.rejects(saveDraft(user,site,post,{article,updatedAt:'old'}),/changed/);
    const saved=await saveDraft(user,site,post,{article:{...article,title:'Edited helpful article'},updatedAt:iso(before!.updated_at)});
    assert.equal(saved.quality.approved,false);
    await assert.rejects(enqueue(user,site,false,'publish',undefined,post),/CMS connection/);
    await assert.rejects(saveMetrics(user,site,post,{periodStart:'2026-02-30',periodEnd:'2026-03-01'}),/completed measurement/);
    await updateSite(user,site,false,{scheduleEnabled:true,scheduleDay:0,scheduleTime:'08:00',timezone:'Australia/Sydney'});
    await query('UPDATE marketing_sites SET next_run_at=$2 WHERE id=$1',[site,new Date(Date.now()-60000)]);
    const now=new Date();await queueDueSchedules(now);await queueDueSchedules(now);
    assert.equal((await one<{n:number}>("SELECT count(*)::int n FROM marketing_jobs WHERE site_id=$1 AND kind='cycle'",[site]))?.n,1);
    await updateSite(user,site,false,{scheduleEnabled:false});
    assert.equal((await one("SELECT status FROM marketing_jobs WHERE site_id=$1 AND kind='cycle'",[site]))?.status,'failed');
    assert.equal((await ownedSite(user,site)).schedule_enabled,false);
    process.env.ADMIN_EMAILS='owner@marketing-qa.invalid';process.env.APP_BASE_URL='https://example.com';process.env.GEMINI_API_KEY='qa-key';process.env.BLOG_GEMINI_MODEL='gemini-qa';
    const stamp=new Date().toISOString();
    await query("UPDATE marketing_sites SET publisher='owtomate' WHERE id=$1",[site]);
    await query('UPDATE marketing_posts SET brief=$2,quality=$3 WHERE id=$1',[post,{week:'2026-10-05',gatheredAt:stamp,sources:[{ref:'S1',url:'https://example.com/',publisher:'Example',title:'Products',excerpt:'Product information',collectedAt:stamp,role:'own'}],searches:[],listingSample:null,unavailable:[]},{approved:true,issues:[],reviewedAt:stamp}]);
    globalThis.fetch=(async()=>new Response(JSON.stringify({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({approved:false,issues:['Claim is unsupported.']})}]}}]}),{status:200})) as typeof fetch;
    await enqueue(user,site,true,'publish',undefined,post);await marketingTick();
    assert.equal((await one('SELECT count(*)::int n FROM blog_posts'))?.n,0);
    assert.equal((await one('SELECT status FROM marketing_posts WHERE id=$1',[post]))?.status,'draft');
    globalThis.fetch=(async()=>new Response(JSON.stringify({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({approved:true,issues:[]})}]}}]}),{status:200})) as typeof fetch;
    await enqueue(user,site,true,'review',undefined,post);await marketingTick();
    await enqueue(user,site,true,'publish',undefined,post);await marketingTick();await marketingTick();
    const published=await one('SELECT * FROM marketing_posts WHERE id=$1',[post]);
    assert.equal(published?.status,'published');assert.ok(published?.blog_post_id);assert.match(published?.published_url,/^https:\/\/example.com\/blog\//);
    assert.equal((await one('SELECT count(*)::int n FROM blog_posts'))?.n,1);
    await assert.rejects(enqueue(user,site,true,'publish',undefined,post),/unpublished draft/);
  } finally {globalThis.fetch=oldFetch;for(const key of keys) if(oldEnv[key]===undefined) delete process.env[key];else process.env[key]=oldEnv[key];await pool.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await pool.end();}
});
